#!/usr/bin/python

import os
import sys

def syntax():
    print "  count_distinct <tablename> <columnname> | <dbalias>"
    sys.exit(1)
    
try:
    tablename=sys.argv[1]
    columnname=sys.argv[2]
except:
    syntax()

os.system('''echo "select count(distinct(%s)) from %s" ''' % (columnname, tablename))
