#!/bin/env python
# usage:

import os
import sys

try:
    tablename=sys.argv[1]
except:
    print("You must specify tablename.")
    sys.exit(1)

os.system("echo 'select count(*) as count from %s'" % tablename)
