#!/bin/env python
#
# convert csv file to media wiki format

import sys
import csv

def syntax(msg=None):
    if msg:
        print(msg)
        print()
    print("csv2wiki <filename>")
    print()
    sys.exit(1)

try:
    filename = sys.argv[1]
except:
    syntax()


# read it
fp=open(filename, 'r')
rows = csv.reader(fp, delimiter=',', escapechar='\\')
table = []
for fields in rows:
    i = 0
    row = []
    for field in fields:
        field = field.strip()
        row.append(field)
        i += 1
    table.append(row)
fp.close()

# output wiki format
print('{| class="wikitable"')
i = 0
for row in table:
    i += 1
    if i == 1:
        delim = '!'
    else:
        delim = '|'
        print("|-")
    print('\n'.join(["%s%s" % (delim, x) for x in row]))

print("|}\n")
    
