#!/usr/bin/python
#
# Format a csv file so that columns line up vertically
#
#   ie. - This:
#
# activity_id,activity_type_id,code,name
# 1,1,entry,Entry,Entered into System
# 2,22,spec-email,Spec Handling Email
#
#   Becomes:
#
# activity_id,  activity_type_id,  code,             name,
# 1,            1,                 entry,            Entry,
# 2,            22,                spec-email,       Spec Handling Email,


import sys
import csv

def syntax(msg=None):
    if msg:
        print msg
        print
    print "csv_format <filename>"
    print
    sys.exit(1)

try:
    filename = sys.argv[1]
except:
    syntax()


fp=open(filename, 'r')

# Init max column lengths:
lengths = [0]*50
table = []

# First pass - get max column lengths
rows = csv.reader(fp, delimiter='|', escapechar='\\')
for fields in rows:
    i = 0
    row = []
    for field in fields:
        field = field.strip()
        lengths[i] = max(len(field), lengths[i])
        row.append(field)
        i += 1
    table.append(row)

# Second pass -- format data:
for row in table:
    i = 0
    line = []
    for field in row:
        if i < len(row)-1:
            s = "%s," % field
            print s.ljust(lengths[i]+1),
        else:
            print field
        i += 1
    
