#!/usr/bin/env python

from os.path import expanduser
from shutil import copyfile
home = expanduser("~")

#TODO: Provide alternative files like zsh_aliases or allow user to pass it in with a flag
filename = '.bash_aliases'
filepath = home + '/' + filename

print 'This command will create an alias for a mysql connection in %s.' % (filepath)

alias = raw_input(" Please provide the database alias you want to use: ")
host = raw_input(" Please provide the database host you want to use: ")
user = raw_input( " Please provide the database user you want to use: ")
password = raw_input(" Please provide the database password you want to use: ")
#port = raw_input( " Please provide the database port you want to use: ")

print "Backing up %s to %s.bak" % (filepath, filepath )
copyfile(filepath, filepath + '.bak')

#use the long versions so that it's more readable
alias_string =  "alias %s='mysql --user=%s --password=%s  --host=%s '\n" % (alias, user, password, host)

fh = open(filepath, 'a')
fh.write(alias_string)
fh.close()

print alias_string + ' added to your .bash_aliases file'
print "To have the alias take affect immediately, please run:"
print "`source %s`" % ( filepath)
