#!/bin/env python

import sys
import copy

from pprint import pprint
import json

def json_pretty(json_data):
    return json.load(json_data)

def syntax():
    print()
    print("   json_pretty <filename>")
    print()
    sys.exit(1)

if __name__ == '__main__':
    args = copy.copy(sys.argv)

    if len(args) < 2:
        syntax()

    filename = args[1]
    fp = sys.stdin if filename == '-' else open(filename, 'r')
    pprint(json_pretty(fp))
