#!/usr/bin/python

import os
import sys

try:
    prog = sys.argv[1]
except:
    print "you must specify python program filename."
    sys.exit(1)
    
#os.system("grep -e 'class ' -e 'def ' %s" % prog)
os.system("cat -n %s | grep -e 'class ' -e 'def '" % prog)
