#!/bin/env python

import os
import sys

def syntax():
    print("  selectmin <tablename> <columnname> | <dbalias>")
    sys.exit(1)
    
try:
    tablename=sys.argv[1]
    columnname=sys.argv[2]
except:
    syntax()

os.system('''echo "select min(%s) from %s " ''' % (columnname, tablename))
