#!/bin/env python

import os
import sys

def syntax():
    print("selecthistogram <tablename> <column> | <db>")
    print("   ie.- selectone batches state")
    sys.exit(1)
    
try:
    tablename=sys.argv[1]
    column=sys.argv[2]
except:
    syntax()

os.system("echo 'select %s, count(*) from %s group by 1'"
          % (column, tablename))
