#!/bin/env python

import os
import sys

def syntax():
    print("  show_create <tablename>")
    sys.exit(1)
    
try:
    tablename=sys.argv[1]
except:
    syntax()

os.system('''echo "show create table %s"''' % tablename)
