#!/usr/bin/env python

import sys
import re
import copy

def sql_pretty(sql, lowercase_kw=False, html=False):
    # Line break and color code:
    keywords = ['select', 'from', 'where', 'order by', 'group by',
                'having', 'limit', 'insert into', 'values']
    # Line break with indentation and color code:
    keywords2 = ['and', 'case', 'else', 'end', 'left join', 'join', 'when']
    # Color code only:
    keywords3 = ['as', 'coalesce', 'on', 'or', 'then']

    #keywords += [k.upper() for k in keywords]
    #keywords2 += [k.upper() for k in keywords2]
    #keywords3 += [k.upper() for k in keywords3]

    if html:
        indent = '&nbsp;' * 3
        nl = '<br \>\n'
        f1 = "<font color='blue'>"
        f1b= "<font color='green'>"
        f2 = '</font>'
    else:
        indent = ' ' * 3
        nl = '\n'
        f1 = ''
        f1b= ''
        f2 = ''

    sql = re.sub(r'\s+', ' ', sql)
    for k in keywords:
        k2 = k if lowercase_kw else '\\1'
        sql = re.sub(r'\b(%s)\s+' % k,
                     r'%s%s%s%s%s%s' % (nl, f1, k2, f2, nl, indent),
                     sql, 0, re.IGNORECASE)
    for k in keywords2:
        k2 = k if lowercase_kw else '\\1'
        sql = re.sub(r'\b(%s)\s+' % k,
                     r'%s%s%s%s%s ' % (nl, indent, f1b, k2, f2),
                     sql, 0, re.IGNORECASE)
    for k in keywords3:
        k2 = k if lowercase_kw else '\\1'
        sql = re.sub(r'\b(%s)\s+' % k,
                     r'%s%s%s ' % (f1b, k2, f2),
                     sql, 0, re.IGNORECASE)

    # Second pass - indent subqueries
    # (To really do this correctly we need a full sql parse)
    sql2 = ''
    ind = ''
    for i, x in enumerate(sql.split(nl)):
        # Start indenting after the second SELECT
        if 'select' in x and i > 1:
            ind = indent*2
        sql2 += '%s%s%s' % (ind, x, nl)
        # Stop indenting after the join's ON statement (hokey I know)
        if re.search(r'\) %sas%s \w+ %son%s' % (f1b, f2, f1b, f2), x):
            ind = ''
    return sql2

def syntax():
    print
    print "   sql_pretty [OPTIONS] <filename>"
    print
    print "       OPTIONS: -l  - lowercase keywords"
    print "                -h  - HTML Output"
    print
    sys.exit(1)

if __name__ == '__main__':
    args = copy.copy(sys.argv)

    # options
    lowercase_kw = False
    if '-l' in args:
        lowercase_kw = True
        pos = args.index('-l')
        args = args[0:pos] + args[pos+1:]

    html = False
    if '-h' in args:
        html = True
        pos = args.index('-h')
        args = args[0:pos] + args[pos+1:]


    if len(args) < 2:
        syntax()

    filename = args[1]
    print sql_pretty(open(filename, 'r').read(),
                     lowercase_kw=lowercase_kw,
                     html=html)

