#!/usr/bin/python

import os
import sys

def syntax():
    print "  tally <tablename> <columnname>| <dbalias>"
    sys.exit(1)
    
try:
    tablename=sys.argv[1]
    columnname=sys.argv[2]
except:
    syntax()

os.system('''echo "select %s, count(*) from %s group by 1 order by 2 desc ;"''' % (columnname, tablename))
